import { ArrowUpRight } from "lucide-react";
import { HeroJourney } from "./hero-journey";
import { FieldGallery, InsideSystem, IntentRouter, Process, Reveal } from "./home-interactions";
import { media } from "./media";
import "./dekoraj-home.css";

export function DekorajHome() {
  return <main className="dk-home" id="main">
    <HeroJourney />
    <div className="dk-marquee" aria-label="Farm construction, automated systems, equipment and technology, project development"><div aria-hidden="true">{[0, 1].map(n => <span key={n}>FARM CONSTRUCTION <i>✳</i> AUTOMATED SYSTEMS <i>✳</i> EQUIPMENT & TECHNOLOGY <i>✳</i> PROJECT DEVELOPMENT <i>✳</i></span>)}</div></div>
    <section className="dk-manifesto dk-wrap" id="explore"><Reveal><span className="dk-eyebrow">01 / The bigger idea</span><h2>WE DON’T JUST<br />BUILD STRUCTURES.<br />WE CONNECT<br /><em>THE WHOLE OPERATION.</em></h2></Reveal><Reveal className="dk-manifesto-note"><span className="dk-cross">✳</span><p>Great operations don’t happen by accident. They are designed, engineered and built with every part in mind.</p><p>We bring farm construction, equipment and agricultural development into one connected conversation.</p><a className="dk-text-link" href="/about">This is Dekoraj <ArrowUpRight size={18} /></a></Reveal></section>
    <section className="dk-build"><img src={media.structure} alt="Farm structure — replace with your exterior photograph" loading="lazy" /><div className="dk-film-shade" /><div className="dk-wrap dk-build-content"><span className="dk-eyebrow">02 / From foundation to function</span><Reveal><h2>AMBITION.<br />MEET <em>INFRASTRUCTURE.</em></h2><p>Commercial farm construction, designed around the way your operation needs to work.</p><a href="/solutions/poultry-infrastructure" className="dk-button">Explore farm construction <ArrowUpRight size={18} /></a></Reveal><div className="dk-build-tags"><span>Site development</span><span>Housing & structures</span><span>Equipment integration</span></div></div></section>
    <InsideSystem /><FieldGallery /><IntentRouter />
    <section className="dk-mart dk-wrap"><Reveal className="dk-section-heading"><div><span className="dk-eyebrow">DekorajMart / Equipment & technology</span><h2>THE TOOLS.<br /><em>BEHIND THE PROGRESS.</em></h2></div><a href="/mart" className="dk-text-link">Explore DekorajMart <ArrowUpRight size={18} /></a></Reveal><div className="dk-product-grid">{[{ name: "Poultry cage systems", image: media.cages, href: "/mart" }, { name: "Feeding & drinking systems", image: media.interior, href: "/mart" }, { name: "Farm infrastructure equipment", image: media.structure, href: "/mart" }].map((p, i) => <a className="dk-product" href={p.href} key={p.name}><div><img src={p.image} alt={`${p.name} — replace with your product image`} loading="lazy" /><span>0{i + 1}</span><ArrowUpRight size={28} /></div><span className="dk-eyebrow">Specifications & quotation on request</span><h3>{p.name}</h3></a>)}</div></section>
    <Process />
    <section className="dk-consult dk-wrap"><Reveal><span className="dk-eyebrow">A conversation that moves you forward</span><h2>YOUR PROJECT.<br /><em>LET’S GET INTO IT.</em></h2></Reveal><div className="dk-consult-grid">{[["online", "Online consultation", "Connect with our team from wherever you are."], ["physical", "In-person consultation", "Talk through your project and equipment needs."], ["site", "Site visitation", "Discuss the realities and opportunities of your site."]].map(([id, title, text]) => <a href={`/consultation?type=${id}`} key={id}><span className="dk-eyebrow">Consultation / {id}</span><h3>{title}</h3><p>{text}</p><span className="dk-text-link">View dates & details <ArrowUpRight size={20} /></span></a>)}</div></section>
    <section className="dk-final"><div className="dk-wrap"><span className="dk-eyebrow">Build with Dekoraj</span><h2>THE NEXT CHAPTER<br /><em>STARTS WITH YOU.</em></h2><a className="dk-button" href="/start-project">Let’s build something <ArrowUpRight size={20} /></a><div className="dk-final-bottom"><span>DEKORAJ GROUP</span><a href="#main">Back to top ↑</a></div></div></section>
  </main>;
}
